apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejiroedwinazkubdeploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ejiroedwinazkubdeploy
  template:
    metadata:
      labels:
        app: ejiroedwinazkubdeploy
    spec:
      containers:
        - name: ejiroedwinazkubdeploy
          image: dev4acr.azurecr.io/ejiroedwinazkubdeploy
          ports:
            - containerPort: 80
